export const REQUEST_LEASE_LIST = 'REQUEST_LEASE_LIST';
export const SUCCESS_LEASE_LIST = 'SUCCESS_LEASE_LIST';
export const FAIL_LEASE_LIST = 'FAIL_LEASE_LIST';



export const REQUEST_LEASE_DETAILS = 'REQUEST_LEASE_DETAILS';
export const SUCCESS_LEASE_DETAILS = 'SUCCESS_LEASE_DETAILS';
export const FAIL_LEASE_DETAILS = 'FAIL_LEASE_DETAILS';